
name: Android Release

on:
  push:
    branches:
      - "dev2"
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> android/key.properties
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17.x"
          cache: gradle
      - name: Get dependencies
        run: flutter pub get

      - name: Flutter action
        uses: subosito/flutter-action@v2.13.0
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.13.0
        with:
         channel: 'stable'
         cache: true
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

        
        

      - name: Upload Android Release
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab

  deploy:
    name: Deploy Android Build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout artifacts
        uses: actions/checkout@v4

      - name: Get Android Build from artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-release
      
