
name: Build Android App

on:
  push:
    branches:
      - "dev2"
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/app/key.properties
          echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> android/app/key.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> android/app/key.properties
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17.x"
          cache: gradle
      - name: Flutter action
        uses: subosito/flutter-action@v2.13.0
      - uses: subosito/flutter-action@v2.13.0
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk --flavor prod --no-tree-shake-icons
      - run: flutter build appbundle --flavor prod --no-tree-shake-icons
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/apk/prod/release/app-prod-release.apk
      - name: Upload Android Release
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab
